{% set name = "RESCRIPt" %}
{% set version = "2023.5.0" %}
{% set sha256 = "bc7aa5e4ae07adb90531a5c9d5f7bd160ae2a1934342c9658e86addaf16d302a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bokulich-lab/RESCRIPt/archive/refs/tags/2023.5.0.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

channels:
  sources:
    - conda-forge
    - bioconda
    - qiime2
    - defaults
  targets:
    - ["conda-forge", "main"]


requirements:
  host:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - ncbi-datasets-pylib >=14.13.0
    - requests
    - xmltodict
    - pandas >=1.4.3
    - vsearch >=2.21.1
    - scikit-learn >=0.24
    - scikit-bio >=0.5
    - q2-types
    - q2-types-genomics >2023.2
    - q2-longitudinal
    - q2-feature-classifier
    - qiime2

test:
  requires:
    - pytest
    - q2-types
    - q2-longitudinal
    - q2-feature-classifier
    - qiime2

  imports:
    - rescript
    - qiime2.plugins.rescript

about:
  home: https://github.com/bokulich-lab/RESCRIPt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'REference Sequence annotation and CuRatIon Pipeline'
  description: |
    RESCRIPt is a python 3 package to support a variety of operations
    for managing and curating reference sequence databases, DNA/RNA
    sequence data, and taxonomic data.
    See citation information below for a full benchmark and description.

extra:
  recipe-maintainers:
    - mirand863
  identifiers:
    - biotools:RESCRIPt
